version: "3"

services:
  hello-docker-react:
    build:
      context: ./docker
      dockerfile: node.Dockerfile
    container_name: cras
    # entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
